default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  template: template0


development:
  <<: *default
  database: rails_task4_development

test:
  <<: *default
  database: rails_task4_test

production:
  <<: *default
  database: rails_task4_production
